language: python
python:
  - "2.7"

before_install:
  - "pip install -r requirements.txt"

script:
  - "cd wilenco"
  - travis_wait "python manage.py test"
  - "coverage run --source=web manage.py test"

after_script: "coveralls"
