language: python
python:
  - "2.7"

before_install:
  -"pip install -r requeriments.txt"

script:
  -"cd wilenco"
  -"python manage.py test"
  -"coverage run --source=web manage.py test"

after_script: "coveralls"
